require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/about_pages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AboutPage. As you add validations to AboutPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AboutPage.create! valid_attributes
      get about_pages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      about_page = AboutPage.create! valid_attributes
      get about_page_url(about_page)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_about_page_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      about_page = AboutPage.create! valid_attributes
      get edit_about_page_url(about_page)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AboutPage" do
        expect {
          post about_pages_url, params: { about_page: valid_attributes }
        }.to change(AboutPage, :count).by(1)
      end

      it "redirects to the created about_page" do
        post about_pages_url, params: { about_page: valid_attributes }
        expect(response).to redirect_to(about_page_url(AboutPage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AboutPage" do
        expect {
          post about_pages_url, params: { about_page: invalid_attributes }
        }.to change(AboutPage, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post about_pages_url, params: { about_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested about_page" do
        about_page = AboutPage.create! valid_attributes
        patch about_page_url(about_page), params: { about_page: new_attributes }
        about_page.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the about_page" do
        about_page = AboutPage.create! valid_attributes
        patch about_page_url(about_page), params: { about_page: new_attributes }
        about_page.reload
        expect(response).to redirect_to(about_page_url(about_page))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        about_page = AboutPage.create! valid_attributes
        patch about_page_url(about_page), params: { about_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested about_page" do
      about_page = AboutPage.create! valid_attributes
      expect {
        delete about_page_url(about_page)
      }.to change(AboutPage, :count).by(-1)
    end

    it "redirects to the about_pages list" do
      about_page = AboutPage.create! valid_attributes
      delete about_page_url(about_page)
      expect(response).to redirect_to(about_pages_url)
    end
  end
end
