require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/terms_pages", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TermsPage. As you add validations to TermsPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TermsPage.create! valid_attributes
      get terms_pages_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      terms_page = TermsPage.create! valid_attributes
      get terms_page_url(terms_page)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_terms_page_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      terms_page = TermsPage.create! valid_attributes
      get edit_terms_page_url(terms_page)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TermsPage" do
        expect {
          post terms_pages_url, params: { terms_page: valid_attributes }
        }.to change(TermsPage, :count).by(1)
      end

      it "redirects to the created terms_page" do
        post terms_pages_url, params: { terms_page: valid_attributes }
        expect(response).to redirect_to(terms_page_url(TermsPage.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TermsPage" do
        expect {
          post terms_pages_url, params: { terms_page: invalid_attributes }
        }.to change(TermsPage, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post terms_pages_url, params: { terms_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested terms_page" do
        terms_page = TermsPage.create! valid_attributes
        patch terms_page_url(terms_page), params: { terms_page: new_attributes }
        terms_page.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the terms_page" do
        terms_page = TermsPage.create! valid_attributes
        patch terms_page_url(terms_page), params: { terms_page: new_attributes }
        terms_page.reload
        expect(response).to redirect_to(terms_page_url(terms_page))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        terms_page = TermsPage.create! valid_attributes
        patch terms_page_url(terms_page), params: { terms_page: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested terms_page" do
      terms_page = TermsPage.create! valid_attributes
      expect {
        delete terms_page_url(terms_page)
      }.to change(TermsPage, :count).by(-1)
    end

    it "redirects to the terms_pages list" do
      terms_page = TermsPage.create! valid_attributes
      delete terms_page_url(terms_page)
      expect(response).to redirect_to(terms_pages_url)
    end
  end
end
